{ type: 'root',
  children: 
   [ { type: 'rule',
       selectors: [ '.h2-ex' ],
       _index: 0,
       children: 
        [ { type: 'declaration',
            property: 'font-size',
            value: '28px',
            _index: 0 },
          { type: 'declaration',
            property: 'margin-bottom',
            value: '20px',
            _index: 1 },
          { type: 'declaration',
            property: 'line-height',
            value: '1.2',
            _index: 2 } ] },
     { type: 'rule',
       selectors: [ '.table td' ],
       _index: 1,
       children: 
        [ { type: 'declaration',
            property: 'word-break',
            value: 'break-all',
            _index: 0 } ] },
     { type: 'rule',
       selectors: [ '.table th' ],
       _index: 2,
       children: 
        [ { type: 'declaration',
            property: 'background',
            value: '#E8E8E8',
            _index: 0 } ] },
     { type: 'rule',
       selectors: [ '.toolbar' ],
       _index: 3,
       children: [] },
     { type: 'rule',
       selectors: [ '.error .label' ],
       _index: 4,
       children: 
        [ { type: 'declaration',
            property: 'color',
            value: 'red',
            _index: 0 } ] },
     { type: 'rule',
       selectors: [ '.collect-tags-red' ],
       _index: 5,
       children: 
        [ { type: 'rule',
            selectors: [ 'a' ],
            _index: 0,
            children: 
             [ { type: 'declaration',
                 property: 'display',
                 value: 'inline-block',
                 _index: 0 },
               { type: 'declaration',
                 property: 'line-height',
                 value: '20px',
                 _index: 1 },
               { type: 'declaration',
                 property: 'border',
                 value: '1px solid #D7D7D7',
                 _index: 2 },
               { type: 'declaration',
                 property: 'border-radius',
                 value: '10px',
                 _index: 3 },
               { type: 'declaration',
                 property: 'background',
                 value: '#F5F4F4',
                 _index: 4 },
               { type: 'declaration',
                 property: 'padding',
                 value: '0 10px',
                 _index: 5 },
               { type: 'declaration',
                 property: 'margin-right',
                 value: '10px',
                 _index: 6 },
               { type: 'declaration',
                 property: 'margin-bottom',
                 value: '10px',
                 _index: 7 } ] },
          { type: 'rule',
            selectors: [ 'a:hover', '.selected' ],
            _index: 1,
            children: 
             [ { type: 'declaration',
                 property: 'background-color',
                 value: '#E22C37',
                 _index: 0 },
               { type: 'declaration',
                 property: 'color',
                 value: '#FFF',
                 _index: 1 },
               { type: 'declaration',
                 property: 'border-color',
                 value: '#D41420',
                 _index: 2 } ] } ] },
     { type: 'rule',
       selectors: [ '.mate-recom .recom-tags' ],
       _index: 6,
       children: [] },
     { type: 'rule',
       selectors: [ '.recom-tags .mate-tit' ],
       _index: 7,
       children: 
        [ { type: 'declaration',
            property: 'margin-bottom',
            value: '15px',
            _index: 0 },
          { type: 'declaration',
            property: 'font-size',
            value: '16px',
            _index: 1 },
          { type: 'declaration',
            property: 'font-weight',
            value: 'bold',
            _index: 2 },
          { type: 'declaration',
            property: 'color',
            value: '#777',
            _index: 3 } ] },
     { type: 'rule',
       selectors: [ '.recom-tags .mate-keywords' ],
       _index: 8,
       children: 
        [ { type: 'declaration',
            property: 'margin-bottom',
            value: '10px',
            _index: 0 } ] },
     { type: 'rule',
       selectors: [ '.mate-keywords .mate-label' ],
       _index: 9,
       children: 
        [ { type: 'declaration',
            property: 'font-weight',
            value: 'bold',
            _index: 0 },
          { type: 'declaration',
            property: 'color',
            value: '#777',
            _index: 1 },
          { type: 'declaration',
            property: 'margin-right',
            value: '18px',
            _index: 2 } ] },
     { type: 'rule',
       selectors: [ '.mate-keywords a' ],
       _index: 10,
       children: 
        [ { type: 'declaration',
            property: 'display',
            value: 'inline-block',
            _index: 0 },
          { type: 'declaration',
            property: 'padding',
            value: '2px 14px',
            _index: 1 },
          { type: 'declaration',
            property: 'margin-right',
            value: '10px',
            _index: 2 },
          { type: 'declaration',
            property: 'background',
            value: '#d3a589',
            _index: 3 },
          { type: 'declaration',
            property: 'font-weight',
            value: 'bold',
            _index: 4 },
          { type: 'declaration',
            property: 'color',
            value: '#fff',
            _index: 5 },
          { type: 'declaration',
            property: 'border-radius',
            value: '15px',
            _index: 6 },
          { type: 'declaration',
            property: 'margin-bottom',
            value: '10px',
            _index: 7 } ] },
     { type: 'rule',
       selectors: [ '.mate-keywords a:hover' ],
       _index: 11,
       children: 
        [ { type: 'declaration',
            property: 'color',
            value: '#fff',
            _index: 0 } ] },
     { type: 'rule',
       selectors: [ '.mate-recom ul' ],
       _index: 12,
       children: 
        [ { type: 'declaration',
            property: 'overflow',
            value: 'hidden',
            _index: 0 },
          { type: 'declaration', property: '*zoom', value: '1', _index: 1 },
          { type: 'declaration',
            property: 'margin-left',
            value: '-20px',
            _index: 2 } ] },
     { type: 'rule',
       selectors: [ '.mate-recom ul li' ],
       _index: 13,
       children: 
        [ { type: 'declaration',
            property: 'float',
            value: 'left',
            _index: 0 },
          { type: 'declaration',
            property: 'margin-left',
            value: '19px',
            _index: 1 },
          { type: 'declaration',
            property: '_display',
            value: 'inline',
            _index: 2 },
          { type: 'declaration',
            property: 'width',
            value: '62px',
            _index: 3 } ] },
     { type: 'rule',
       selectors: [ '.mate-recom .recom-imgs' ],
       _index: 14,
       children: [] },
     { type: 'rule',
       selectors: [ '.recom-imgs img' ],
       _index: 15,
       children: 
        [ { type: 'declaration',
            property: 'width',
            value: '62px',
            _index: 0 },
          { type: 'declaration',
            property: 'height',
            value: '62px',
            _index: 1 },
          { type: 'declaration',
            property: 'display',
            value: 'block',
            _index: 2 } ] },
     { type: 'rule',
       selectors: [ '.recom-imgs a' ],
       _index: 16,
       children: 
        [ { type: 'declaration',
            property: 'display',
            value: 'inline-block',
            _index: 0 },
          { type: 'declaration',
            property: 'width',
            value: '62px',
            _index: 1 },
          { type: 'declaration',
            property: 'height',
            value: '62px',
            _index: 2 },
          { type: 'declaration',
            property: 'position',
            value: 'relative',
            _index: 3 },
          { type: 'declaration',
            property: 'border-radius',
            value: '5px',
            _index: 4 },
          { type: 'declaration',
            property: 'overflow',
            value: 'hidden',
            _index: 5 } ] },
     { type: 'rule',
       selectors: [ '.recom-imgs .recom-title' ],
       _index: 17,
       children: 
        [ { type: 'declaration',
            property: 'display',
            value: 'block',
            _index: 0 },
          { type: 'declaration',
            property: 'position',
            value: 'absolute',
            _index: 1 },
          { type: 'declaration', property: 'left', value: '0', _index: 2 },
          { type: 'declaration', property: 'bottom', value: '0', _index: 3 },
          { type: 'declaration',
            property: 'width',
            value: '62px',
            _index: 4 },
          { type: 'declaration',
            property: 'background',
            value: 'url(http://gtms01.alicdn.com/tps/i1/T1053dFeJgXXaaD1Dr-3-3.png) repeat',
            _index: 5 },
          { type: 'declaration',
            property: 'background',
            value: 'rgba(51,51,51,0.3)',
            _index: 6 },
          { type: 'declaration',
            property: 'height',
            value: '22px',
            _index: 7 },
          { type: 'declaration',
            property: 'line-height',
            value: '22px',
            _index: 8 },
          { type: 'declaration',
            property: 'text-align',
            value: 'center',
            _index: 9 },
          { type: 'declaration',
            property: 'color',
            value: '#fff',
            _index: 10 } ] },
     { type: 'rule',
       selectors: [ '.recom-imgs .recom-img-price' ],
       _index: 18,
       children: 
        [ { type: 'declaration',
            property: 'font-weight',
            value: 'bold',
            _index: 0 },
          { type: 'declaration',
            property: 'color',
            value: '#777',
            _index: 1 } ] },
     { type: 'rule',
       selectors: [ '.recom-imgs .recom-img-price em' ],
       _index: 19,
       children: 
        [ { type: 'declaration',
            property: 'font-weight',
            value: 'bold',
            _index: 0 },
          { type: 'declaration',
            property: 'color',
            value: '#aaa',
            _index: 1 },
          { type: 'declaration',
            property: 'margin-left',
            value: '4px',
            _index: 2 } ] } ] }
